# Generated by Django 4.1.7 on 2023-03-05 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='position',
            new_name='position_id',
        ),
    ]
