# Generated by Django 4.1.7 on 2023-03-05 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_rename_position_employees_position_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employees',
            new_name='Employee',
        ),
        migrations.RenameModel(
            old_name='EmployeeDocuments',
            new_name='EmployeeDocument',
        ),
    ]
