# Generated by Django 4.1.7 on 2023-03-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
