# Generated by Django 4.1.7 on 2023-03-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email_customer',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='website_customer',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
