# Generated by Django 4.1.7 on 2023-03-03 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DAILY', 'daily'), ('WEEKLY', 'weekly'), ('MONTHLY', 'monthly'), ('COMPLAINT', 'complaint'), ('OTHER', 'other')], max_length=100)),
                ('status', models.CharField(choices=[('PLANNED', 'planned'), ('IN_PROGRESS', 'in_progress'), ('COMPLETED', 'completed'), ('CONFIRMED', 'confirmed'), ('OVERDUE', 'overdue'), ('DECLINED', 'declined'), ('OTHER', 'other')], max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('object_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.object')),
            ],
        ),
    ]
