# Generated by Django 4.1.7 on 2023-03-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'planned'), ('IN_PROGRESS', 'in_progress'), ('COMPLETED', 'completed'), ('CONFIRMED', 'confirmed'), ('OVERDUE', 'overdue'), ('DECLINED', 'declined'), ('OTHER', 'other')], default='PLANNED', max_length=100),
        ),
    ]
